name: build arm64 python

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - arm64/python/**
      
jobs:
  push:
    name: "arm64:python_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./arm64/python
          file: ./arm64/python/${{ matrix.tag }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/sullivanshosting/arm64:python_${{ matrix.tag }}
